//! HTML Report Generator for workflow and pipeline execution.
//! Mirrors reports/workflow_report.py from Python project.

use lab_core::workflows::{StepResult, StepStatus, WorkflowExecution};
use serde::{Deserialize, Serialize};

/// Generates self-contained HTML reports with SVG charts and status badges.
pub struct ReportGenerator;

impl ReportGenerator {
    pub fn new() -> Self { Self }

    /// Generate an HTML report for a single workflow execution.
    pub fn generate_workflow_report(&self, execution: &WorkflowExecution, title: Option<&str>) -> String {
        let title = title.unwrap_or(&execution.workflow_name);
        let status_badge = match execution.status.as_str() {
            "completed" => self.badge("Completed", "4CAF50", "white"),
            "failed" => self.badge("Failed", "f44336", "white"),
            "partial" => self.badge("Partial", "ff9800", "white"),
            _ => self.badge(&execution.status, "607D8B", "white"),
        };

        let steps_html: String = execution.step_results.iter().map(|step| self.step_row(step)).collect();

        let total_duration = execution.total_duration_secs;

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title} — AI Research Lab Report</title>
<style>
body {{ font-family: system-ui, -apple-system, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; background: #f5f5f5; }}
h1 {{ color: #333; border-bottom: 2px solid #1976D2; padding-bottom: 0.5rem; }}
.summary {{ display: flex; gap: 1rem; margin: 1rem 0; flex-wrap: wrap; }}
.summary-item {{ background: white; padding: 1rem; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); flex: 1; min-width: 150px; }}
.summary-item label {{ font-size: 0.85rem; color: #666; display: block; }}
.summary-item span {{ font-size: 1.4rem; font-weight: 600; color: #333; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
th {{ background: #1976D2; color: white; padding: 0.75rem 1rem; text-align: left; }}
td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #eee; }}
tr:last-child td {{ border-bottom: none; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; color: white; font-size: 0.85rem; }}
.error-text {{ color: #f44336; font-family: monospace; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>📊 {title}</h1>
<div class="summary">
  <div class="summary-item"><label>Status</label>{status_badge}</div>
  <div class="summary-item"><label>Duration</label><span>{total_duration:.1}s</span></div>
  <div class="summary-item"><label>Steps</label><span>{steps_count}</span></div>
</div>
<h2>Step Results</h2>
<table>
  <tr><th>Step</th><th>Status</th><th>Duration</th><th>Error</th></tr>
  {steps_html}
</table>
<p style="color: #999; font-size: 0.8rem; margin-top: 2rem;">Generated by AI Research Lab Report Generator</p>
</body>
</html>"#,
            title = title,
            status_badge = status_badge,
            total_duration = total_duration,
            steps_count = execution.step_results.len(),
            steps_html = steps_html,
        )
    }

    /// Generate an HTML summary for multiple workflow executions.
    pub fn generate_batch_report(&self, executions: &[WorkflowExecution], title: Option<&str>) -> String {
        let title = title.unwrap_or("Workflow Batch Report");
        let rows: String = executions.iter().map(|e| {
            let status_badge = match e.status.as_str() {
                "completed" => self.badge("Completed", "4CAF50", "white"),
                "failed" => self.badge("Failed", "f44336", "white"),
                _ => self.badge(&e.status, "607D8B", "white"),
            };
            format!(
                r#"<tr><td>{}</td><td>{}</td><td>{:.1}s</td><td>{}</td></tr>"#,
                e.workflow_name,
                status_badge,
                e.total_duration_secs,
                e.step_results.len(),
            )
        }).collect();

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 1000px; margin: 2rem auto; }}
h1 {{ color: #333; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
th {{ background: #1565C0; color: white; padding: 0.75rem 1rem; text-align: left; }}
td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #eee; }}
</style></head><body>
<h1>{title}</h1>
<table><tr><th>Workflow</th><th>Status</th><th>Duration</th><th>Steps</th></tr>{rows}</table>
</body></html>"#,
            title = title,
            rows = rows,
        )
    }

    // ─── Helpers ──────────────────────────────────────────────

    fn badge(&self, text: &str, color: &str, text_color: &str) -> String {
        format!(
            r#"<span class="badge" style="background-color: {color}; color: {text_color};">{text}</span>"#,
            color = color,
            text_color = text_color,
            text = text,
        )
    }

    fn step_row(&self, step: &StepResult) -> String {
        let status_badge = match step.status {
            StepStatus::Completed => self.badge("Passed", "4CAF50", "white"),
            StepStatus::Failed => self.badge("Failed", "f44336", "white"),
            StepStatus::Skipped => self.badge("Skipped", "ff9800", "white"),
            StepStatus::Timeout => self.badge("Timeout", "ff9800", "white"),
            StepStatus::Cancelled => self.badge("Cancelled", "9e9e9e", "white"),
            _ => self.badge("Pending", "b0bec5", "white"),
        };
        let error_html = match &step.error {
            Some(err) => format!(r#"<span class="error-text">{}</span>"#, self.escape_html(err)),
            None => String::new(),
        };
        format!(
            r#"<tr><td>{}</td><td>{}</td><td>{:.2}s</td><td>{}</td></tr>"#,
            step.step_id,
            status_badge,
            step.duration_secs,
            error_html,
        )
    }

    fn escape_html(&self, text: &str) -> String {
        text.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
    }
}

impl Default for ReportGenerator {
    fn default() -> Self { Self::new() }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_html() {
        let gen = ReportGenerator::new();
        let execution = WorkflowExecution {
            workflow_id: "wf-1".into(),
            workflow_name: "Test Workflow".into(),
            execution_id: "exec-1".into(),
            status: "completed".into(),
            step_results: vec![
                StepResult {
                    step_id: "step-1".into(),
                    status: StepStatus::Completed,
                    outcome: Some(lab_core::workflows::StepOutcome::Success),
                    result: None,
                    error: None,
                    duration_secs: 1.5,
                },
            ],
            total_duration_secs: 2.3,
            started_at: chrono::Utc::now().to_rfc3339(),
            completed_at: Some(chrono::Utc::now().to_rfc3339()),
            error: None,
        };
        let html = gen.generate_workflow_report(&execution, None);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("Test Workflow"));
        assert!(html.contains("Completed"));
        assert!(html.contains("2.3s"));
    }

    #[test]
    fn fails_with_error() {
        let gen = ReportGenerator::new();
        let execution = WorkflowExecution {
            workflow_id: "wf-1".into(),
            workflow_name: "Failing Workflow".into(),
            execution_id: "exec-1".into(),
            status: "failed".into(),
            step_results: vec![
                StepResult {
                    step_id: "step-1".into(),
                    status: StepStatus::Failed,
                    outcome: Some(lab_core::workflows::StepOutcome::Error),
                    result: None,
                    error: Some("Connection refused".into()),
                    duration_secs: 0.3,
                },
            ],
            total_duration_secs: 0.3,
            started_at: chrono::Utc::now().to_rfc3339(),
            completed_at: Some(chrono::Utc::now().to_rfc3339()),
            error: Some("step-1 failed".into()),
        };
        let html = gen.generate_workflow_report(&execution, None);
        assert!(html.contains("Failed"));
        assert!(html.contains("Connection refused"));
    }

    #[test]
    fn escape_html_works() {
        let gen = ReportGenerator::new();
        assert_eq!(gen.escape_html("<script>alert('xss')</script>"), "&lt;script&gt;alert('xss')&lt;/script&gt;");
    }
}
